import java.util.*;

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        HashMap<Character, Integer> smap = new HashMap<>();
        for (int i=0; i<s.length(); i++) {
            if (smap.containsKey(s.charAt(i))) {
                smap.put(s.charAt(i), smap.get(s.charAt(i))+1);
            } else {
                smap.put(s.charAt(i), 1);
            }
        }
        HashMap<Character, Integer> tmap = new HashMap<>();
        for (int i=0; i<t.length(); i++) {
            if (tmap.containsKey(t.charAt(i))) {
                tmap.put(t.charAt(i), tmap.get(t.charAt(i))+1);
            } else {
                tmap.put(t.charAt(i), 1);
            }
        }
        Set<Character> keys = tmap.keySet();
        for (Character x : keys) {
            if (!smap.containsKey(x)) {
                return x;
            }
            if (smap.get(x)<tmap.get(x)) {
                return x;
            }
        }
        return ' ';
    }
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        scan.close();
    }
}
